"""empty message

Revision ID: 368018eaf70c
Revises: c4c3b6911265
Create Date: 2019-11-11 12:26:02.586526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368018eaf70c'
down_revision = 'c4c3b6911265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('email_', sa.String(length=120), nullable=True))
    op.drop_constraint('data_email_key', 'data', type_='unique')
    op.create_unique_constraint(None, 'data', ['email_'])
    op.drop_column('data', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'data', type_='unique')
    op.create_unique_constraint('data_email_key', 'data', ['email'])
    op.drop_column('data', 'email_')
    # ### end Alembic commands ###
